### PR TITLE
Destructor bomb

### PR DESCRIPTION
**Pull request by Munksgaard**
Introduce destructor-bombs to improve the (runtime) safety of the library.

### CODE REVIEW

**Comment by Manishearth** [comment]
It may be possible to avoid using the extra bool field by prematurely running drop (manually) in `close()`, [like so](http://is.gd/Pvmj8Z)

This means we would have to do the following in `close()`:

```rust
fn close(mut self) {
 // create some dummy values to place inside
 // this is safe because nobody will read these
 let mut sender = unsafe { mem::uninitialized() };
 let mut receiver = unsafe { mem::uninitialized() };
 // extract the internal sender/receiver so that we can drop them
 mem::swap(&mut self.0, &mut sender);
 mem::swap(&mut self.1, &mut receiver);

 drop(sender);drop(receiver); // drop them
 mem::forget(self); // Ensure destructors don't run
}
```

The [implementation of `mem::swap`](http://manishearth.github.io/rust-internals-docs/std/mem/fn.forget.html#example) uses the same combination of creating an `uninitialized()` scratch space and `forget`ing it before it can get accessed.

Sadly, we cannot move out of types implementing destructors, otherwise the above impl could just destructure and drop the components. Instead, we have to do some trickery.

**Comment by Munksgaard** [comment]
That is certainly another possibility. It keeps the Chan implementation simple, but perhaps your implementation of `close` would throw some people off? Also, do you have any ideas what the performance would be like?

**Comment by Manishearth** [comment]
Just leave an elaborate comment and it should be fine.

It's not inefficient; we do the same thing `drop()` does (without calling `Drop::drop()`), and we additionally allocate stack space for a dummy sender/receiver pair. Not heavy at all.

**Comment by Munksgaard** [comment]
Cool. Do you wanna do a PR?

**Comment by Manishearth** [comment]
Updated this one

**Comment by Munksgaard** [comment]
Before we merge this, I think we should make sure that it wont hinder @laumann's port of Servo too much (https://github.com/laumann/servo/tree/session-types). Obviously, destructor-bombs like these shouldn't have an impact on correctly designed programs, but because the Servo port is the main use case of this library so far, it'd be nice to test before we merge this PR.

**Comment by laumann** [comment]
In the Servo code I've taken great pains to properly close channels (and have considered it an error when this didn't happen).

**Comment by setir** [comment]
I think this could be moved to compile time, like so (sorry for the pseudo rust):

enum Completed {}
impl<E> Chan<E, Eps> { pub fn close(self) -> Completed { return unsafe { /*create Completed*/ } } }

then
fn atm(c: Chan<(), Atm>) -> Completed { ... /*must run till "return c.close()"*/ }

**Comment by Manishearth** [comment]
That can't stop the destructor from running. Moving it to compile time requires linear types, which Rust doesn't have (not counting humpty_dumpty, which is an approximation)

**Comment by setir** [comment]
I guess, the goal is not to stop the destructor from running, but to prevent (unintentional) non conforming implementation.

One way is the runtime bomb, but another is my proposal of protocol-complete marker.

**Comment by Manishearth** [comment]
The thing is, even with a protocol-complete marker, you can't force folks to reach that marker in highly concurrent code (we can't just wrap it in a function like above because the protocol may be enacted over many steps via structs and stuff, and branch off).

**Comment by setir** [comment]
Of course it must be voluntary :), but if you want the compiler to help you catch your errors, this is a way, without runtime overhead. (Me being a rust outsider, I don't know, but it might be possible to pass around the channel with the necessary information, so that even in highly concurrent code, the type checker can help catch unfinished runs.)

**Comment by Munksgaard** [comment]
Hi @setir, thanks for contributing :smile: 

That is definitely an interesting idea, and one that was somewhat suggested at our recent presentation of the library at WGP. 

As I understand it, your idea is somewhat similar to having a function like the following

```rust
fn start_session<P: HasDual>(Fn(P) -> Eps, Fn(P::Dual) -> Eps)
```

instead of the `session_channel()` function that we provide. That is, a function that takes two functions as input, and runs them as the opposite sides of a session, requiring that both return `Eps` (or `Completed`).

I agree that this would ensure that both protocols run to completion, but I believe the lack of flexibility would cause some problems for us. For instance, It would become much harder to set up more complex communication networks: How would you set up a network consisting of three processes all talking to each other using only `start_session`? The way I see it, you would almost certainly need to rely on other primitives, like Rust's builtin channels, because `start_session` only supports two processes at a time.

**Comment by Munksgaard** [comment]
@laumann: Let's merge this as well, shall we?

**Pull request merged**
