### PR TITLE
Change the license to MIT

### PR DESCRIPTION
**Pull request by Munksgaard**
We've had several suggestions for this, and it turns out to be necessary for the inclusion of our library in Servo, so we have decided to switch to the MIT license.

We will also need to publish a new version on crates.io once this has been merged.

### CODE REVIEW

**Comment by laumann** [comment]
Apart from my name, everything looks good - is this the licence @larsbergstrom recommended?

**Comment by laumann** [comment]
I guess we should also bump the version?

**Comment by Munksgaard** [comment]
Yeah, that's we one. We should bump the version, but perhaps merge at least #22 first? Perhaps #23 can wait.

**Comment by larsbergstrom** [comment]
Thanks for making the change - much appreciated!

**Pull request merged**
