### PR TITLE
Remove accept, request, and borrow versions

### PR DESCRIPTION
**Pull request by Munksgaard**
These functions aren't used any more, confuse users and clutter the
namespace.

All occurences of code like

```rust
let (tx, rx) = channel();
let t1 = spawn(move || srv(accept(tx).unwrap()));
let t2 = spawn(move || cli(request(rx).unwrap()));
```

can be replaced by the shorter and nicer

```rust
let (c1, c2) = session_channel();
let t1 = spawn(move || srv(c1));
let t2 = spawn(move || cli(c2));
```

For the tests to still pass, we need to remove the issue-8 compile-fail
test, which tested against a soundness bug in request.

### CODE REVIEW

**Comment by Munksgaard** [comment]
This fails because the compile-fail directory does not exist when empty. I'll add a basic compile-fail test.

**Comment by Munksgaard** [comment]
We could use more of those anyway, to showcase what our library does.

**Comment by Munksgaard** [comment]
#21 will try to add some more tests.

**Comment by Munksgaard** [comment]
@laumann: r?

**Comment by laumann** [comment]
r+

**Pull request merged**
