### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by Munksgaard**

### CODE REVIEW

**Comment by Munksgaard** [comment]
@laumann: Perhaps you want to add the atm example from the article (in case you've already written it down)?

**Comment by laumann** [comment]
Sure, I'll add it

**Comment by laumann** [comment]
How about the POP3 examples?

**Comment by Munksgaard** [comment]
Sure, the more the merrier :-)

**Comment by Munksgaard** [comment]
I've taken a look at the pop3 example, and I think it needs some work before it's ready to be included. It's not very pretty at the moment. I'll merge this, then we can always add pop3 later.

**Pull request merged**
